services:
  tw-power-plant:
    build: .
    # Or use image: if you're using a pre-built image
    ports:
      - "8090:80"
    volumes:
      - ./data:/app/data
    environment:
      - TRMNL_PLUGIN_API_KEY=${TRMNL_PLUGIN_API_KEY}
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - tw-power-plant
    environment:
      - TUNNEL_URL=http://power-plant
    restart: unless-stopped